markdown: kramdown
highlighter: rouge
paginate: 100
language: 'en-uk'
words_per_minute: 200

# Jekyll GitHub Pages settings
baseurl: "" # Leave blank if this is your main user page
url: "https://yourusername.github.io" # Replace with your actual GitHub Pages URL

# Site info
title: Your Blog
description: A Jekyll blog using Jasper2
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
favicon: assets/images/favicon.png

# Social
navigation: true
subscribers: false
twitter: yourhandle
facebook: yourpage

# Comments & Analytics
disqus: false
google_analytics: ""

# Permalinks
permalink: /:title

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

feed:
  path: feed.xml

# Exclude these from the build
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - Rakefile
  - .travis.yml
